name: Build and Push
on: 
  [workflow_dispatch]
jobs: 
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Version
        run: |
          docker compose version