name: Build and Push to Dockerhub
on: 
  push
jobs: 
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Version
        run: |
          docker compose version

      - name: Build
        run: |
          docker context use default
          docker compose build

      - name: Login
        run: |
          docker login -u davingreg -p${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push
        run: |
          docker compose push davingreg/laraveldavin:latest
          docker logout