name: Build and Push to GHCR

on: 
  push

jobs: 
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Image
        run: |
          docker context use default
          docker login -u GregoriusDavin -p${{ secrets.GH_PAT }} ghcr.io
          docker build -t ghcr.io/davingreg/laraveldavin:latest

      - name: Push to GHCR and Logout
        run: |
          docker push ghcr.io/davingreg/laraveldavin:latest
          docker logout